services:
  discord-bot-monitoring:
    build:
      context: .
      target: production
    tty: true
    volumes:
      - ./config.toml:/app/config.toml
    ports:
      - 80:8000
    env_file:
      - .env
