services:
  discord-bot-monitoring:
    image: ghcr.io/airopi/discord-bot-monitoring:master
    tty: true
    init: true
    volumes:
      - ./config.toml:/app/config.toml
    env_file:
      - .env
    ports:
      - 80:8000 # run behind a rev proxy with https
    restart: unless-stopped
